apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 5
  parallelism: 3
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      containers:
      - name: my-container
        image: luksa/batch-job
      restartPolicy: Never